# -*- coding: utf-8 -*-
"""Копия блокнота "GOST_RAG_Pipeline.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCBm_BAUZ8J0U0bBpxzKdLLtf6jO68-5

# 🏛️ RAG-пайплайн для базы знаний ГОСТ Р 77.*

Этот ноутбук строит локальную RAG-систему поверх репозитория [arasskazov/gost-kb](https://github.com/arasskazov/gost-kb).

**Что делает:**
- Загружает все `full.md` из GitHub
- Строит векторный индекс (ChromaDB + многоязычные эмбеддинги)
- Отвечает на вопросы через DeepSeek API

**Порядок запуска:** выполняйте ячейки сверху вниз (Shift+Enter).

---
**Время первого запуска:** ~5–10 минут (загрузка модели эмбеддингов ~1.2 GB)  
**Последующие запуски:** ~1–2 минуты (если сессия Colab не перезапускалась)

## Шаг 1 — Установка зависимостей
"""

# %%capture
!pip install llama-index llama-index-vector-stores-chroma llama-index-embeddings-huggingface
!pip install chromadb sentence-transformers openai
print('✅ Зависимости установлены')

"""## Шаг 2 — Введите ваш DeepSeek API ключ"""

# Шаг 2 — задаём ключ напрямую (без getpass)
DEEPSEEK_API_KEY = "sk-fb4ae2bb4e574cb9aded98a2a0dc86ad"
print("✅ Ключ сохранён")

"""## Шаг 3 — Загрузка всех стандартов из GitHub"""

import requests
from llama_index.core import Document

STANDARDS = [
    '77-001', '77-002', '77-101', '77-102',
    '77-301', '77-302', '77-303', '77-304',
    '77-305', '77-306', '77-402', '77-403', '77-404'
]
BASE_URL = 'https://raw.githubusercontent.com/arasskazov/gost-kb/main'

documents = []
failed = []

for std in STANDARDS:
    # Загружаем full.md
    url_full = f'{BASE_URL}/standards/lci/{std}/full.md'
    r = requests.get(url_full, timeout=15)
    if r.status_code == 200 and len(r.text) > 100:
        documents.append(Document(
            text=r.text,
            metadata={'standard': std, 'source': url_full, 'type': 'full'}
        ))
        print(f'  ✅ {std}: {len(r.text):,} символов')
    else:
        failed.append(std)
        print(f'  ❌ {std}: не загружен (статус {r.status_code})')

    # Загружаем summary.md как дополнительный документ
    url_sum = f'{BASE_URL}/standards/lci/{std}/summary.md'
    r2 = requests.get(url_sum, timeout=15)
    if r2.status_code == 200 and len(r2.text) > 50:
        documents.append(Document(
            text=r2.text,
            metadata={'standard': std, 'source': url_sum, 'type': 'summary'}
        ))

print(f'\n📚 Загружено документов: {len(documents)}')
if failed:
    print(f'⚠️  Не загружены: {failed}')

"""## Шаг 4 — Построение векторного индекса

> ⏳ Первый запуск займёт 5–8 минут: скачивается модель эмбеддингов ~1.2 GB
"""

import chromadb
from llama_index.core import VectorStoreIndex, StorageContext, Settings
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

print('🔄 Загружаем модель эмбеддингов (multilingual-e5-large)...')
embed_model = HuggingFaceEmbedding(
    model_name='intfloat/multilingual-e5-large',
    max_length=512
)
Settings.embed_model = embed_model
print('✅ Модель загружена')

# ChromaDB в памяти (достаточно для работы в Colab)
chroma_client = chromadb.EphemeralClient()
chroma_collection = chroma_client.get_or_create_collection(
    'gost_standards',
    metadata={'hnsw:space': 'cosine'}
)
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

print('🔄 Индексируем документы...')
index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
    show_progress=True
)
print(f'\n✅ Индекс построен: {len(documents)} документов')



!pip install llama_index llama_index.llms.openai_like
import llama_index
import llama_index.llms.openai_like

"""## Шаг 5 — Настройка DeepSeek и поискового движка"""

from llama_index.llms.openai_like import OpenAILike
from llama_index.core import Settings

SYSTEM_PROMPT = """Ты — эксперт-нормировщик по стандартам серии ГОСТ Р 77.* \
(управление жизненным циклом изделий).

Правила:
1. Отвечай ТОЛЬКО на основе предоставленных фрагментов стандартов.
2. Всегда указывай номер ГОСТ и раздел/пункт (например: ГОСТ Р 77.001, п. 3.4).
3. Если информация в предоставленных фрагментах отсутствует — так и скажи,
   не придумывай нормы.
4. При противоречиях между стандартами — укажи оба варианта с источниками.
5. Используй точные формулировки из текста стандарта."""

llm = OpenAILike(
    model='deepseek-chat',
    api_base='https://api.deepseek.com',
    api_key=DEEPSEEK_API_KEY,
    temperature=0.1,
    max_tokens=2048,
    is_chat_model=True,
    system_prompt=SYSTEM_PROMPT
)
Settings.llm = llm

# Поисковый движок: топ-6 релевантных чанков
query_engine = index.as_query_engine(
    similarity_top_k=6,
    response_mode='compact'
)
print('✅ Поисковый движок готов')

"""## Шаг 6 — Задаём вопросы!

Измените текст в переменной `question` и запустите ячейку.
"""

def ask(question: str, show_sources: bool = True):
    print(f'\n❓ Вопрос: {question}')
    print('─' * 60)
    response = query_engine.query(question)
    print(f'💬 Ответ:\n{response}')
    if show_sources:
        print('\n📎 Источники:')
        seen = set()
        for node in response.source_nodes:
            std = node.metadata.get('standard', '?')
            src_type = node.metadata.get('type', '?')
            score = node.score or 0
            key = f'{std}/{src_type}'
            if key not in seen:
                print(f'  → {std} ({src_type}), релевантность: {score:.3f}')
                seen.add(key)
    return response

# ── Пример 1: базовый вопрос ──────────────────────────────────────────────
ask('Что такое жизненный цикл изделия и какие стадии он включает?')

# ── Пример 2: поиск по конкретному стандарту ─────────────────────────────
ask('Какова область применения ГОСТ 77.102?')

# ── Пример 3: сравнительный запрос ───────────────────────────────────────
ask('В чём разница между понятиями "изделие" и "продукт" в стандартах серии 77?')

# ── Ваш вопрос ───────────────────────────────────────────────────────────
question = 'Введите ваш вопрос здесь'
ask(question)

"""## Шаг 7 — Интерактивный режим (чат)

Запустите ячейку и вводите вопросы в поле ввода.  
Введите `выход` для остановки.
"""

print('🤖 ГОСТ-эксперт готов. Задавайте вопросы (введите "выход" для остановки)\n')
while True:
    q = input('Вопрос: ').strip()
    if not q or q.lower() in ('выход', 'exit', 'quit'):
        print('Сессия завершена.')
        break
    ask(q)

"""---
## 📝 Советы

**Хорошие вопросы для этой базы:**
- *Что означает термин X по ГОСТ 77.001?*
- *Какие требования к документации на стадии разработки?*
- *Какие стандарты серии 77 регулируют вопросы утилизации?*
- *Перечислите ключевые термины из ГОСТ 77.301*

**Если сессия Colab перезапустилась:**  
Нужно снова выполнить все ячейки (Runtime → Run all).  
Индекс пересоздастся за ~5 минут.

**Обновление базы (при появлении новых стандартов):**  
Добавьте номер нового стандарта в список `STANDARDS` в Шаге 3 и перезапустите с Шага 3.

**Стоимость DeepSeek API:**  
deepseek-chat стоит $0.27/1M токенов (вход) и $1.10/1M (выход).  
Один типичный запрос к этой базе ≈ $0.001–0.003.

"""
